// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trpcdemo.proto

package com.jackie.trpc.service;

public final class ComplexProto {
  private ComplexProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jackie_trpc_Mydata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jackie_trpc_Mydata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jackie_trpc_Mydata_NodeStateEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jackie_trpc_Mydata_NodeStateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jackie_trpc_Mydata_NodeState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jackie_trpc_Mydata_NodeState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jackie_trpc_Mydata_NodeState_ConveyorContainerAttribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jackie_trpc_Mydata_NodeState_ConveyorContainerAttribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jackie_trpc_ProcessDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jackie_trpc_ProcessDataRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016trpcdemo.proto\022\017com.jackie.trpc\"\210\006\n\006My" +
      "data\022\014\n\004code\030\001 \001(\t\022:\n\nnode_state\030\002 \003(\0132&" +
      ".com.jackie.trpc.Mydata.NodeStateEntry\022\022" +
      "\n\nwork_state\030\003 \001(\t\022\014\n\004zone\030\004 \001(\t\032S\n\016Node" +
      "StateEntry\022\013\n\003key\030\001 \001(\005\0220\n\005value\030\002 \001(\0132!" +
      ".com.jackie.trpc.Mydata.NodeState:\0028\001\032\274\004" +
      "\n\tNodeState\022\017\n\007node_id\030\001 \001(\005\022\025\n\rhas_cont" +
      "ainer\030\002 \001(\010\022\026\n\016container_code\030\003 \001(\t\022\026\n\016l" +
      "ast_read_time\030\004 \001(\003\022\030\n\020last_report_time\030" +
      "\005 \001(\003\022\037\n\027last_leave_success_time\030\006 \001(\003\022\037" +
      "\n\027last_has_container_time\030\007 \001(\003\022Y\n\023conta" +
      "iner_attribute\030\010 \001(\0132<.com.jackie.trpc.M" +
      "ydata.NodeState.ConveyorContainerAttribu" +
      "te\022\026\n\016container_task\030\t \001(\t\022\022\n\ngroup_code" +
      "\030\n \001(\t\032\363\001\n\032ConveyorContainerAttribute\022\016\n" +
      "\006height\030\001 \001(\003\022\016\n\006length\030\002 \001(\003\022\r\n\005width\030\003" +
      " \001(\003\022\016\n\006weight\030\004 \001(\003\022\020\n\010material\030\005 \001(\003\022\023" +
      "\n\013orientation\030\006 \001(\t\022\020\n\010sku_info\030\007 \001(\t\022\027\n" +
      "\017abnormal_reason\030\010 \001(\t\022\035\n\025group_abnormal" +
      "_reason\030\t \001(\t\022\016\n\006qrcode\030\n \001(\t\022\025\n\rabnorma" +
      "l_code\030\013 \001(\003\"\'\n\022ProcessDataRequest\022\021\n\tre" +
      "dis_key\030\001 \001(\t2Z\n\013DataService\022K\n\013ProcessD" +
      "ata\022#.com.jackie.trpc.ProcessDataRequest" +
      "\032\027.com.jackie.trpc.MydataB)\n\027com.jackie." +
      "trpc.serviceB\014ComplexProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_jackie_trpc_Mydata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jackie_trpc_Mydata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jackie_trpc_Mydata_descriptor,
        new java.lang.String[] { "Code", "NodeState", "WorkState", "Zone", });
    internal_static_com_jackie_trpc_Mydata_NodeStateEntry_descriptor =
      internal_static_com_jackie_trpc_Mydata_descriptor.getNestedTypes().get(0);
    internal_static_com_jackie_trpc_Mydata_NodeStateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jackie_trpc_Mydata_NodeStateEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_jackie_trpc_Mydata_NodeState_descriptor =
      internal_static_com_jackie_trpc_Mydata_descriptor.getNestedTypes().get(1);
    internal_static_com_jackie_trpc_Mydata_NodeState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jackie_trpc_Mydata_NodeState_descriptor,
        new java.lang.String[] { "NodeId", "HasContainer", "ContainerCode", "LastReadTime", "LastReportTime", "LastLeaveSuccessTime", "LastHasContainerTime", "ContainerAttribute", "ContainerTask", "GroupCode", });
    internal_static_com_jackie_trpc_Mydata_NodeState_ConveyorContainerAttribute_descriptor =
      internal_static_com_jackie_trpc_Mydata_NodeState_descriptor.getNestedTypes().get(0);
    internal_static_com_jackie_trpc_Mydata_NodeState_ConveyorContainerAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jackie_trpc_Mydata_NodeState_ConveyorContainerAttribute_descriptor,
        new java.lang.String[] { "Height", "Length", "Width", "Weight", "Material", "Orientation", "SkuInfo", "AbnormalReason", "GroupAbnormalReason", "Qrcode", "AbnormalCode", });
    internal_static_com_jackie_trpc_ProcessDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jackie_trpc_ProcessDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jackie_trpc_ProcessDataRequest_descriptor,
        new java.lang.String[] { "RedisKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
