// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trpcdemo.proto

package com.jackie.trpc.service;

public interface ProcessDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jackie.trpc.ProcessDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string redis_key = 1;</code>
   * @return The redisKey.
   */
  java.lang.String getRedisKey();
  /**
   * <code>string redis_key = 1;</code>
   * @return The bytes for redisKey.
   */
  com.google.protobuf.ByteString
      getRedisKeyBytes();
}
