package com.jackie.trpc.service;

import com.tencent.trpc.core.rpc.RpcContext;
import com.tencent.trpc.core.rpc.anno.TRpcMethod;
import com.tencent.trpc.core.rpc.anno.TRpcService;
import java.util.concurrent.CompletionStage;


/**
 * Generated by trpc-java-codegen
 */
@TRpcService(name = "com.jackie.trpc.DataService")
public interface DataServiceAsyncAPI {

    /**
     * ProcessData
     *
     * @param context context
     * @param request request
     * @return {@link CompletionStage} of {@link Mydata}
     */
    @TRpcMethod(name = "ProcessData")
    CompletionStage<Mydata> processData(RpcContext context, ProcessDataRequest request);
}