// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trpcdemo.proto

package com.jackie.trpc.service;

public interface MydataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jackie.trpc.Mydata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>map&lt;int32, .com.jackie.trpc.Mydata.NodeState&gt; node_state = 2;</code>
   */
  int getNodeStateCount();
  /**
   * <code>map&lt;int32, .com.jackie.trpc.Mydata.NodeState&gt; node_state = 2;</code>
   */
  boolean containsNodeState(
      int key);
  /**
   * Use {@link #getNodeStateMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.jackie.trpc.service.Mydata.NodeState>
  getNodeState();
  /**
   * <code>map&lt;int32, .com.jackie.trpc.Mydata.NodeState&gt; node_state = 2;</code>
   */
  java.util.Map<java.lang.Integer, com.jackie.trpc.service.Mydata.NodeState>
  getNodeStateMap();
  /**
   * <code>map&lt;int32, .com.jackie.trpc.Mydata.NodeState&gt; node_state = 2;</code>
   */

  /* nullable */
com.jackie.trpc.service.Mydata.NodeState getNodeStateOrDefault(
      int key,
      /* nullable */
com.jackie.trpc.service.Mydata.NodeState defaultValue);
  /**
   * <code>map&lt;int32, .com.jackie.trpc.Mydata.NodeState&gt; node_state = 2;</code>
   */

  com.jackie.trpc.service.Mydata.NodeState getNodeStateOrThrow(
      int key);

  /**
   * <code>string work_state = 3;</code>
   * @return The workState.
   */
  java.lang.String getWorkState();
  /**
   * <code>string work_state = 3;</code>
   * @return The bytes for workState.
   */
  com.google.protobuf.ByteString
      getWorkStateBytes();

  /**
   * <code>string zone = 4;</code>
   * @return The zone.
   */
  java.lang.String getZone();
  /**
   * <code>string zone = 4;</code>
   * @return The bytes for zone.
   */
  com.google.protobuf.ByteString
      getZoneBytes();
}
