// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trpcdemo.proto

package com.jackie.trpc.service;

/**
 * Protobuf type {@code com.jackie.trpc.ProcessDataRequest}
 */
public final class ProcessDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.jackie.trpc.ProcessDataRequest)
    ProcessDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProcessDataRequest.newBuilder() to construct.
  private ProcessDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProcessDataRequest() {
    redisKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProcessDataRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jackie.trpc.service.ComplexProto.internal_static_com_jackie_trpc_ProcessDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jackie.trpc.service.ComplexProto.internal_static_com_jackie_trpc_ProcessDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jackie.trpc.service.ProcessDataRequest.class, com.jackie.trpc.service.ProcessDataRequest.Builder.class);
  }

  public static final int REDIS_KEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object redisKey_;
  /**
   * <code>string redis_key = 1;</code>
   * @return The redisKey.
   */
  @java.lang.Override
  public java.lang.String getRedisKey() {
    java.lang.Object ref = redisKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      redisKey_ = s;
      return s;
    }
  }
  /**
   * <code>string redis_key = 1;</code>
   * @return The bytes for redisKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRedisKeyBytes() {
    java.lang.Object ref = redisKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      redisKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(redisKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, redisKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(redisKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, redisKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jackie.trpc.service.ProcessDataRequest)) {
      return super.equals(obj);
    }
    com.jackie.trpc.service.ProcessDataRequest other = (com.jackie.trpc.service.ProcessDataRequest) obj;

    if (!getRedisKey()
        .equals(other.getRedisKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REDIS_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getRedisKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jackie.trpc.service.ProcessDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jackie.trpc.service.ProcessDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.jackie.trpc.ProcessDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.jackie.trpc.ProcessDataRequest)
      com.jackie.trpc.service.ProcessDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jackie.trpc.service.ComplexProto.internal_static_com_jackie_trpc_ProcessDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jackie.trpc.service.ComplexProto.internal_static_com_jackie_trpc_ProcessDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jackie.trpc.service.ProcessDataRequest.class, com.jackie.trpc.service.ProcessDataRequest.Builder.class);
    }

    // Construct using com.jackie.trpc.service.ProcessDataRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      redisKey_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jackie.trpc.service.ComplexProto.internal_static_com_jackie_trpc_ProcessDataRequest_descriptor;
    }

    @java.lang.Override
    public com.jackie.trpc.service.ProcessDataRequest getDefaultInstanceForType() {
      return com.jackie.trpc.service.ProcessDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.jackie.trpc.service.ProcessDataRequest build() {
      com.jackie.trpc.service.ProcessDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jackie.trpc.service.ProcessDataRequest buildPartial() {
      com.jackie.trpc.service.ProcessDataRequest result = new com.jackie.trpc.service.ProcessDataRequest(this);
      result.redisKey_ = redisKey_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jackie.trpc.service.ProcessDataRequest) {
        return mergeFrom((com.jackie.trpc.service.ProcessDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jackie.trpc.service.ProcessDataRequest other) {
      if (other == com.jackie.trpc.service.ProcessDataRequest.getDefaultInstance()) return this;
      if (!other.getRedisKey().isEmpty()) {
        redisKey_ = other.redisKey_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              redisKey_ = input.readStringRequireUtf8();

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object redisKey_ = "";
    /**
     * <code>string redis_key = 1;</code>
     * @return The redisKey.
     */
    public java.lang.String getRedisKey() {
      java.lang.Object ref = redisKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redisKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string redis_key = 1;</code>
     * @return The bytes for redisKey.
     */
    public com.google.protobuf.ByteString
        getRedisKeyBytes() {
      java.lang.Object ref = redisKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redisKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string redis_key = 1;</code>
     * @param value The redisKey to set.
     * @return This builder for chaining.
     */
    public Builder setRedisKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      redisKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string redis_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRedisKey() {
      
      redisKey_ = getDefaultInstance().getRedisKey();
      onChanged();
      return this;
    }
    /**
     * <code>string redis_key = 1;</code>
     * @param value The bytes for redisKey to set.
     * @return This builder for chaining.
     */
    public Builder setRedisKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      redisKey_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.jackie.trpc.ProcessDataRequest)
  }

  // @@protoc_insertion_point(class_scope:com.jackie.trpc.ProcessDataRequest)
  private static final com.jackie.trpc.service.ProcessDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jackie.trpc.service.ProcessDataRequest();
  }

  public static com.jackie.trpc.service.ProcessDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProcessDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<ProcessDataRequest>() {
    @java.lang.Override
    public ProcessDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProcessDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProcessDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jackie.trpc.service.ProcessDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

